id: I7E277818
legacy_id: P006678
ocr_import_info:
  bdrc_scan_id: W23933
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T00:48:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:18:14.488357+00:00'
last_modified: 2022-09-02 13:19:27.322331
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23933
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23933
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དམ་པའི་ཆོས་མངོན་པ་ཀུན་ལས་བཏུས་པའི་འགྲེལ་པ་ཤེས་བྱ་རབ་གསལ་སྣང་བ།
  author: སློབ་དཔོན་ཐོགས་མེད།
statistics:
  ocr_word_mean_confidence_index: 0.759184943161975
  ocr_word_median_confidence_index: 0.8299999833106995
quality: null
bases:
  I3632:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3632
      total_pages: 526
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3632.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7404649783245356
    legacy_id: v002
  I3550:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3550
      total_pages: 576
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3550.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7748395913127563
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
